baseURL = "https://netbrain.github.io/brreg-history/"
title = "Brreg Historie"
languageCode = "nb-NO"

# Disable features we don't need
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "section"]
